### ISSUE TITLE
Not working with 10.0

### ISSUE THREAD

**Issue by l3uGsY** [AlexFolland/BattlegroundSpiritReleaser#1]
It pops out no errors, just doesn't do anything.

**Comment by BujuArena** [comment]
I haven't been playing BGs, and I'm only playing Wrath Classic these days.  If someone wants to make a pull request to fix this, I will gladly check it out and merge it if it supports both Wrath Classic and mainline.

**Comment by BujuArena** [comment]
I've pushed a release which may resolve the issue.  Can you please try it and report back?

**Comment by BujuArena** [comment]
I'm guessing it's fixed since nobody's reported otherwise in almost 2 years.
