### ISSUE TITLE
Not working on Retail 11.0

### ISSUE THREAD

**Issue by Tanae** [AlexFolland/BattlegroundSpiritReleaser#2]
7x ...egroundSpiritReleaser/BattlegroundSpiritReleaser.lua:132: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@BattlegroundSpiritReleaser/BattlegroundSpiritReleaser.lua"]:132: in main chunk

Locals:
BattlegroundSpiritReleaserDBDefaults = <table> {
 Enabled = true
 SoulstoneDelay = 0
 UseSoulstone = true
}
maxSoulstoneDelay = 20
optionsMenu = BattlegroundSpiritReleaserOptionsMenu {
 name = "BattlegroundSpiritReleaser"
}
enabledCheckButton = BattlegroundSpiritReleaserEnabledCheckButton {
 Text = BattlegroundSpiritReleaserEnabledCheckButtonText {
 }
 text = BattlegroundSpiritReleaserEnabledCheckButtonText {
 }
}
useSoulstoneCheckButton = BattlegroundSpiritReleaserUseSoulstoneCheckButton {
 Text = BattlegroundSpiritReleaserUseSoulstoneCheckButtonText {
 }
 text = BattlegroundSpiritReleaserUseSoulstoneCheckButtonText {
 }
}
soulstoneDelayLabel = BattlegroundSpiritReleaserSoulstoneDelayLabel {
}
soulstoneDelayEditBox = BattlegroundSpiritReleaserSoulstoneDelayEditBox {
 Right = Texture {
 }
 Left = Texture {
 }
 Middle = Texture {
 }
}
soulstoneDelaySlider = BattlegroundSpiritReleaserSoulstoneDelaySlider {
 PixelSnapDisabled = true
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}
(*temporary) = nil
(*temporary) = BattlegroundSpiritReleaserOptionsMenu {
 name = "BattlegroundSpiritReleaser"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"

**Comment by BujuArena** [comment]
I've committed a possible fix, but not published a release.  Can you please test the latest commit from the `master` branch in mainline WoW?

**Comment by Tanae** [comment]
Sure. I'll report back if there's issues or not so you can push out a release. Thanks for your dedication to the addon.

**Comment by Tanae** [comment]
Everything is working perfectly now. Thank you again! You're amazing!

**Comment by BujuArena** [comment]
Thanks for the report.  I'll publish a release now.
